### ISSUE TITLE
Elevation and Status icons overlap

### ISSUE THREAD

**Issue by iamthetot** [elizeuangelo/fvtt-module-z-scatter#1]
Elevation indicators and status indicators stay in the center of a square when two or more tokens are getting re-positioned. Even when only one token has them, this is jarring, and worse when multiple have them because they overlap.

It's basically the only thing I can find wrong with this otherwise awesome QoL improvements.

https://puu.sh/JBzwQ/8455598c8f.gif

**Comment by elizeuangelo** [comment]
Fixed in commit 26d47062ed52feddd62664a8c96243360d5da932

New release [v1.2.1](https://github.com/elizeuangelo/fvtt-module-z-scatter/releases/tag/v1.2.1)
