### ISSUE TITLE
A setting to ignore invisible tokens.

### ISSUE THREAD

**Issue by GuitarGuyNick** [elizeuangelo/fvtt-module-z-scatter#12]
the issue i have is that when there are tokens that are foundry hidden/invisible. not status hidden or invisible. it moves player tokens often putting them off center alerting them that something is on the map. 

the fix i would like is to have a setting where if a token is invisible it has the z scatter effect but only on the side of the gm. it doesnt affect the token of the player at all. if this is possible. 

the secondary fix is just to ignore invisible tokens entirely.  the first fix would be prefereable because it would allow the gm to have more control over tokens that occupy other spaces without players knowing.

**Comment by elizeuangelo** [comment]
> the fix i would like is to have a setting where if a token is invisible it has the z scatter effect but only on the side of the gm. it doesnt affect the token of the player at all. if this is possible.

I'm a little bit confused because I believe this is already how the module works? Even if your token seems dislocated on the GM screen, it shouldnt affect on the player side.

**Comment by GuitarGuyNick** [comment]
> > the fix i would like is to have a setting where if a token is invisible it has the z scatter effect but only on the side of the gm. it doesnt affect the token of the player at all. if this is possible.
> 
> I'm a little bit confused because I believe this is already how the module works? Even if your token seems dislocated on the GM screen, it shouldnt affect on the player side.

if thats the case then great i dont really look at player view that much.
