### ISSUE TITLE
[Bug] Broken in FVTT v12

### ISSUE THREAD

**Issue by ChasarooniZ** [elizeuangelo/fvtt-module-z-scatter#13]

**Comment by ottyn** [comment]
Module somewhat works in v12.  Passing over a token in a square does shift the tokens properly, but then moving back out of the square does not move the token back into original position.  So the token remains off-center.

**Comment by thejoester** [comment]
Also once tokens are shifted, they no longer select properly. You can click on the token but the box around it to indicate it is selected is not there and it sometimes stops becoming movable with the mouse, can only move with arrow keys.

**Comment by elizeuangelo** [comment]
> Module somewhat works in v12. Passing over a token in a square does shift the tokens properly, but then moving back out of the square does not move the token back into original position. So the token remains off-center.

I'm testing and I can't replicate this? Are you still having this issue?

**Comment by apoapostolov** [comment]
As of latest version minutes ago, it seems that you can select and move the tokens but the border around the selected token is not displayed.

**Comment by ScoflWorks** [comment]
> @elizeuangelo As of latest version minutes ago, it seems that you can select and move the tokens but the border around the selected token is not displayed.

Specifically, it appears that the token border is shifted over by a large margin when scattered tokens are hovered, and remain so even if they are moved off the same square or if "Size Snap" is turned off.

![image](https://github.com/user-attachments/assets/e25b1de1-c571-48f8-9015-43cec93acf96)

> Module somewhat works in v12. Passing over a token in a square does shift the tokens properly, but then moving back out of the square does not move the token back into original position. So the token remains off-center.

This appears to occur with certain modules (Drag Ruler and Elevation Ruler both caused this issue in D&D5e), as well as the PF2e system, when the scene has "Token Vision" is enabled. Other systems may also have this issue.
![image](https://github.com/user-attachments/assets/adb7f182-ec25-426d-b4c9-50739efb6b38)
![image](https://github.com/user-attachments/assets/9f629409-96e0-4dd7-a338-246b12b2d75d)

**Comment by Fridan99** [comment]
any news about v12 compatibility?

**Comment by elizeuangelo** [comment]
I almost fixed everything but there is still a bug pending. I'm finding it hard to find the time but when I do I will make a release, sorry about the delay.
