### ISSUE TITLE
Request for v12 compatibility

### ISSUE THREAD

**Issue by weepingminotaur** [elizeuangelo/fvtt-module-z-scatter#14]
Pretty much what the title says. :)

This is such a useful module; v12 compatibility would be amazing.

**Comment by Fridan99** [comment]
+1

**Comment by Fridan99** [comment]
the module seems to works perfectly, probably its a versioning problem

**Comment by elizeuangelo** [comment]
I'm not having much time lately, but I will try fixing this module on the weekend!

**Comment by Fridan99** [comment]
> I'm not having much time lately, but I will try fixing this module on the weekend!


Great, I love this module and I think many users do too.  I think this is the must typical to have module.

**Comment by elizeuangelo** [comment]
I'm testing on v12 and it seems working fine. I'm simply going to update the manifest. Ty fall!
