### ISSUE TITLE
Targeting and status icons aren't moved along with the image

### ISSUE THREAD

**Issue by shemetz** [elizeuangelo/fvtt-module-z-scatter#2]
![image](https://user-images.githubusercontent.com/6516621/225035950-fcca9b02-c450-435d-ba7b-1d2a8f720fab.png)

It would be great if this was solved!  Either by shifting them as well, or by making the actual token position shift (X and Yin canvas-space) rather than just the visual image.

**Comment by elizeuangelo** [comment]
Fixed in e71199054747935f64d360d951232fb13d70831f

Checkout [v1.2.4](https://github.com/elizeuangelo/fvtt-module-z-scatter/releases/tag/v1.2.4)

**Comment by shemetz** [comment]
![image](https://user-images.githubusercontent.com/6516621/225074647-0214f08e-d53b-4469-b11c-4b5c80d66997.png)
awesome!
