### ISSUE TITLE
Bug when moving scattered tokens with keyboard: they are moved based on top-left corner, rather than actual position

### ISSUE THREAD

**Issue by shemetz** [elizeuangelo/fvtt-module-z-scatter#5]
Before & after selecting the token and pressing the W button (for Up 1 square):

![image](https://user-images.githubusercontent.com/6516621/225076827-8475ee19-57de-4627-9931-344861886fe4.png)

![image](https://user-images.githubusercontent.com/6516621/225076879-285a96ec-82e6-4d89-b380-d412f2a8289e.png)

Here's my theorized explanation for this bug:

![image](https://user-images.githubusercontent.com/6516621/225077119-5da8941d-2fd6-42a3-b543-77b9e43d05a4.png)

**Comment by elizeuangelo** [comment]
I can't reproduce this either, please me call me in Discord: Magus#9576

**Comment by shemetz** [comment]
I think your comments for this and for the other task were accidentally swapped?  This bug happens with other modules disabled, and is probably the core foundry bug you mentioned.

**Comment by elizeuangelo** [comment]
Idk in version 1.2.5 I "fix" the broken function using a:

```
canvas.grid.grid.getGridPositionFromPixels = function (x, y) {
	let gs = canvas.dimensions!.size;
	return [Math.floor(y / gs + 0.5), Math.floor(x / gs + 0.5)];
};
```

I will remove that code when its fixed in core foundry, but it shouldnt be bugged as it is in your game.

Whats the system and foundry version you are using?

**Comment by Dorako** [comment]
https://user-images.githubusercontent.com/1561190/225118188-7a689d7e-aa5a-44e0-b762-1d02d4e4964c.mp4

I think this is the same issue as shemetz is describing. The two tokens are occupying the same tile, but a single move 'away' from the stack is resulting in more than one 'tile' of movement.

**Comment by elizeuangelo** [comment]
Im also testing in Pathfinder 2 and using the exact same Foundry version, but I cant replicate this. Could you test it with all modules disabled?

**Comment by Dorako** [comment]
https://user-images.githubusercontent.com/1561190/225124513-b92e6e5f-2ece-4bf7-9dcd-cb3e4c3d2b8c.mp4

Here's a video with only Module Management+ and Developer Mode enabled.

**Comment by elizeuangelo** [comment]
Hm... maybe this is a bug related to the map configuration? Whats your grid size?

**Comment by elizeuangelo** [comment]
I will soon release a v1.2.6 wich is not a stable release, but please use it and test if its working now

**Comment by Dorako** [comment]
https://user-images.githubusercontent.com/1561190/225159998-7a49efdd-501b-4d92-b5d9-11496be5ed51.mp4
Seems to work. I'm off to bed and then work, so it'll be a while until I can respond again.

**Comment by shemetz** [comment]
Seemed to work perfectly for me in 1.2.7!
