### ISSUE TITLE
Add github url to module manifest

### ISSUE THREAD

**Issue by nschoenwald** [elizeuangelo/fvtt-module-z-scatter#7]
It would be nice to have the github url in the module manifest like other modules do it.
From what I can see, you just need to add this to module.json:
`"url": "https://github.com/elizeuangelo/fvtt-module-z-scatter",`

**Comment by shemetz** [comment]
This was done in https://github.com/elizeuangelo/fvtt-module-z-scatter/pull/10 and can be closed.
