### ISSUE TITLE
Request: Add a function that returns the token's X and Y values

### ISSUE THREAD

**Issue by mclemente** [elizeuangelo/fvtt-module-z-scatter#8]
Hello, a user of this module requested for Health Estimate to support Z Scatter (https://github.com/mclemente/healthEstimate/issues/156), since it shares the issue of the Token HUD that it uses the token's size to be rendered.

So, I want to request a helper function to figure out a token's X and Y values that were used for the reposition since there isn't a way to find out the rotation, offset and pos values.

**Comment by elizeuangelo** [comment]
You could get their token position in the grid with `token.mesh.x` and `token.mesh.y`.

But I think the best scenario is copying their tooltip coordinates?
`token.tooltip.x` and `token.tooltip.y`

```
function setHE(t) {
    t.healthEstimate.x = t.tooltip.x;
    t.healthEstimate.y = t.tooltip.y - 63;
}
```

**Comment by mclemente** [comment]
TIL about token.tooltip.

That function did it for me. Only issue is when set to always render the estimate it is bugged on loading a canvas, but that can't be fixed by us since we don't get to choose which hook is called first and can be fixed with a simple hover.

>I believe HealthEstimate always has a fixed offset in relation to it, on the Y coordinate equal to -63.

You just made me realise I reverted the logic, it was meant to be -65 only as a fallback.
